### ISSUE TITLE
Unknown type error(s) occurred in github.com/hashicorp/terraform/internal/rpcapi

### ISSUE THREAD

**Issue by cpkr162** [ZOSOpenTools/terraformport#2]
/u/chamap1/terraformport:>wharf ./terraform/...

Build errors occurred in: github.com/hashicorp/terraform/internal/rpcapi
Package require manual porting: github.com/hashicorp/terraform/internal/rpcapi
	unknown type error(s) occurred in github.com/hashicorp/terraform/internal/rpcapi: [stacks.go:326:14: cannot infer Message (grpc_helpers.go:43:2) stacks.go:165:14: cannot infer Message (grpc_helpers.go:43:2)]
Backed up workspace to /u/chamap1/terraformport/go.work.backup

**Comment by v1gnesh** [comment]
Hi,

I had to make only one change to one terraform source file. The rest were on dependencies.
Apart from that, think the actions remain mostly the same as written here - https://github.com/orgs/ZOSOpenTools/discussions/281#discussioncomment-5895257.
There is an upstream issue for swapping the readline implementation to a maintained fork.
It hasn't received much action yet unfortunately.

**Comment by cpkr162** [comment]
> Hi,
> 
> I had to make only one change to one terraform source file. The rest were on dependencies. Apart from that, think the actions remain mostly the same as written here - https://github.com/orgs/ZOSOpenTools/discussions/281#discussioncomment-5895257. There is an upstream issue for swapping the readline implementation to a maintained fork. It hasn't received much action yet unfortunately.

Thank you @v1gnesh , I will gothrough the link

**Comment by v1gnesh** [comment]
Fixed in https://github.com/ZOSOpenTools/terraformport/pull/7.
